"""Regenerate tests/native/jpeg3_fixture.h: the payload of a DefineBitsJPEG3 tag.

Why this exists rather than a hand-written byte array: hand-written JPEG bytes do
not decode, and the SWF extractor's own probe rejects an undecodable payload with
a silent `continue`. An invalid fixture therefore makes the test that uses it pass
without ever reaching the code under test -- which is exactly what happened when
the first version of this was a literal array, and why it took three attempts to
notice. The payload here is produced by a real encoder and verified to decode
before it is written, and the C++ test asserts the same property at run time so a
fixture that later stops decoding fails rather than passing vacuously.

The generated header is committed, so this script is *not* part of the test run:
it needs Pillow, which the test suite deliberately does not require. Run it by
hand after changing the fixture, and expect the committed header to be unchanged
if you did not.
"""
import os
import struct

OUT = os.path.join(os.path.dirname(__file__), "jpeg3_fixture.h")

# The JPEG has to be a *real* one. Hand-assembled entropy-coded data does not
# decode -- and the extractor's own probe rejects an undecodable payload with a
# silent `continue`, so an invalid fixture makes the test pass without ever
# reaching the code it is meant to cover. So it is encoded here, not typed.
import io
import zlib

from PIL import Image


def encode_jpeg(width: int, height: int) -> bytes:
    """A greyscale baseline JPEG of the given size, via a real encoder."""
    buf = io.BytesIO()
    Image.new("L", (width, height), 128).save(buf, format="JPEG", quality=85)
    return buf.getvalue()


JPEG = encode_jpeg(2, 2)

# One fully-opaque alpha byte per pixel, zlib-compressed. The extractor's inflate
# must accept it, so it is produced by zlib rather than written by hand.
ALPHA = zlib.compress(bytes([0xFF] * 4), 9)

# Verify before emitting: a fixture that does not decode makes the test vacuous.
im = Image.open(io.BytesIO(JPEG))
im.load()
assert im.size == (2, 2), f"encoded {im.size}, expected (2, 2)"
print(f"JPEG decodes: {im.size} {im.mode}, {len(JPEG)} bytes")

assert JPEG[:2] == b"\xff\xd8" and JPEG[-2:] == b"\xff\xd9", "not a JPEG"
assert zlib.decompress(ALPHA) == bytes([0xFF] * 4), "alpha is not a valid zlib stream"

lines = ["// Generated by tests/native/make_jpeg3_fixture.py -- do not edit by hand.",
         "//",
         "// A 2x2 baseline JPEG and a 2x2 zlib alpha channel: the exact payload of",
         "// a DefineBitsJPEG3 tag. Hand-written JPEG bytes do not decode, and the",
         "// extractor's own probe rejects an undecodable payload silently, so the",
         "// fixture has to be real or the test asserts nothing.",
         "//",
         "// Committed rather than generated by the test run, because encoding it",
         "// needs Pillow and the suite must not grow a dependency to check a",
         "// fixture it already holds.",
         "#pragma once",
         "",
         "namespace jpeg3_fixture {",
         "",
         "inline const unsigned char jpeg[] = {"]
row = []
for i, b in enumerate(JPEG):
    row.append(f"0x{b:02X},")
    if len(row) == 12:
        lines.append("    " + " ".join(row))
        row = []
if row:
    lines.append("    " + " ".join(row))
lines += ["};", "", "inline const unsigned char alpha[] = {"]
row = []
for b in ALPHA:
    row.append(f"0x{b:02X},")
    if len(row) == 12:
        lines.append("    " + " ".join(row))
        row = []
if row:
    lines.append("    " + " ".join(row))
lines += ["};", "", "}  // namespace jpeg3_fixture", ""]

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}: jpeg {len(JPEG)}B, alpha {len(ALPHA)}B")
