// Regression tests for MohoReader.
//
// The fixtures are generated by tests/flash_fixtures/generate_moho_fixtures.py
// and cover the cases a Moho reader has to survive: a minimal rig, a switch
// layer, the older 1021 format generation that omits whole fields, a skeleton
// with a dangling parent index, and several ways a file can be rejected.
//
// Run: moho_tests <fixtureDir>
#include <windows.h>

#include "MohoReader.h"
#include "tsystem.h"

#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <cstdio>
#include <string>

// Qt5 spells this QStringList::join, not QString::join.
static QString joined(const QStringList &l) {
    return l.join(QStringLiteral(", "));
}

static int gFail = 0;
static int gChecks = 0;

static void check(bool ok, const char *what, const QString &detail = {}) {
    ++gChecks;
    fprintf(stderr, "   [%s] %s", ok ? "ok  " : "FAIL", what);
    if (!detail.isEmpty())
        fprintf(stderr, "  (%s)", qPrintable(detail));
    fprintf(stderr, "\n");
    if (!ok) ++gFail;
}

typedef Moho::Container (*FnDetect)(const TFilePath &);
typedef bool (*FnRead)(const TFilePath &, Moho::Document &);
typedef int (*FnManifest)(const TFilePath &, const Moho::Document &,
                          const TFilePath &);

static FnDetect g_detect;
static FnRead g_read;
static FnManifest g_manifest;

static Moho::Document load(const QString &dir, const QString &name,
                           bool expectOk = true) {
    Moho::Document d;
    const bool ok = g_read(TFilePath(QDir(dir).filePath(name).toStdString()), d);
    if (expectOk && !ok)
        fprintf(stderr, "   (unexpectedly failed to read %s: %s)\n",
                qPrintable(name), qPrintable(d.error));
    return d;
}

int main(int argc, char **argv) {
    QCoreApplication app(argc, argv);
    if (argc < 2) {
        fprintf(stderr, "   usage: moho_tests <fixtureDir>\n");
        return 2;
    }
    const QString dir = QString::fromLocal8Bit(argv[1]);

    HMODULE core = LoadLibraryA(
        "C:\\Users\\charl\\Documents\\Flare\\build_local\\RelWithDebInfo\\"
        "tnzcore.dll");
    if (!core) {
        fprintf(stderr, "   could not load tnzcore.dll (err %lu)\n",
                (unsigned long)GetLastError());
        return 1;
    }
    g_detect = (FnDetect)GetProcAddress(
        core, "?detectContainer@Moho@@YA?AW4Container@1@AEBVTFilePath@@@Z");
    g_read = (FnRead)GetProcAddress(
        core, "?read@Moho@@YA_NAEBVTFilePath@@AEAUDocument@1@@Z");
    g_manifest = (FnManifest)GetProcAddress(
        core, "?writeManifest@Moho@@YAHAEBVTFilePath@@AEBUDocument@1@0@Z");
    if (!g_detect || !g_read || !g_manifest) {
        fprintf(stderr, "   tnzcore.dll is missing the Moho reader\n");
        return 1;
    }

    // ---- container detection is by content, not by extension --------------
    fprintf(stderr, "\n-- container detection --\n");
    check(g_detect(TFilePath(QDir(dir)
                                .filePath("minimal_rig.moho")
                                .toStdString())) == Moho::Container::Zip,
          ".moho is a ZIP container");
    check(g_detect(TFilePath(QDir(dir)
                                .filePath("minimal_rig.mohoproj")
                                .toStdString())) == Moho::Container::RawJson,
          ".mohoproj is a bare document");
    check(g_detect(TFilePath(QDir(dir)
                                .filePath("legacy.anme")
                                .toStdString())) == Moho::Container::Legacy,
          ".anme is recognised as the pre-11 format");
    check(g_detect(TFilePath(QDir(dir)
                                .filePath("plain.zip")
                                .toStdString())) == Moho::Container::Zip,
          "a non-Moho ZIP still reads as a ZIP");
    check(g_detect(TFilePath("nope.moho")) == Moho::Container::Unknown,
          "a missing file is Unknown");

    // ---- both container forms give the same document ----------------------
    fprintf(stderr, "\n-- container equivalence --\n");
    {
        const Moho::Document zipped = load(dir, "minimal_rig.moho");
        const Moho::Document bare = load(dir, "minimal_rig.mohoproj");
        check(zipped.valid && bare.valid, "both forms parse");
        check(zipped.totalLayers == bare.totalLayers,
              "both forms report the same layer count",
              QString("%1 vs %2").arg(zipped.totalLayers).arg(bare.totalLayers));
        check(zipped.bones.size() == bare.bones.size(),
              "both forms report the same bone count");
        check(zipped.keyframes == bare.keyframes,
              "both forms report the same keyframe count");
    }

    // ---- a minimal rig ----------------------------------------------------
    fprintf(stderr, "\n-- minimal rig --\n");
    {
        const Moho::Document d = load(dir, "minimal_rig.moho");
        check(d.valid, "parsed");
        check(d.version == 1038, "format version read",
              QString::number(d.version));
        check(d.width == 800 && d.height == 600, "canvas read",
              QString("%1x%2").arg(d.width).arg(d.height));
        check(qFuzzyCompare(d.fps, 24.0), "frame rate read", QString::number(d.fps));
        check(d.totalLayers == 2, "both layers counted",
              QString::number(d.totalLayers));
        check(d.layerTypes.value("BoneLayer") == 1, "BoneLayer counted");
        check(d.layerTypes.value("MeshLayer") == 1, "MeshLayer counted");
        check(d.bones.size() == 1, "one bone", QString::number(d.bones.size()));
        check(d.bones.first().name == "Root", "bone name read",
              d.bones.first().name);
        check(d.bones.first().parent == -1, "root bone has no parent");
        // Three channels in this fixture: the bone's anim_angle (3 keys), the
        // mesh point's position (2 keys) and its width (1 key) -- 6 keyframes.
        // A nested layer's channels must be counted once, not once per parent.
        check(d.keyframeTracks == 3, "channel tracks found",
              QString::number(d.keyframeTracks));
        check(d.keyframes == 6, "keyframes counted",
              QString::number(d.keyframes));
        check(d.actions == 1, "action name registered",
              QString::number(d.actions));
        check(d.meshPoints == 1, "mesh point counted");
    }

    // ---- switch layers ----------------------------------------------------
    fprintf(stderr, "\n-- switch layer --\n");
    {
        const Moho::Document d = load(dir, "switch_layer.moho");
        check(d.valid, "parsed");
        check(d.switches.size() == 1, "switch layer found",
              QString::number(d.switches.size()));
        if (!d.switches.isEmpty()) {
            const Moho::Switch &s = d.switches.first();
            check(s.name == "Mouth", "switch named", s.name);
            check(s.alternatives.size() == 2, "two alternatives",
                  QString::number(s.alternatives.size()));
            check(s.alternatives.contains("MouthA") &&
                      s.alternatives.contains("MouthB"),
                  "alternatives are the child layer names");
            // The channel holds names, not indices.
            check(s.activeChild == "MouthA",
                  "active child resolved from the key value", s.activeChild);
        }
    }

    // ---- the older format generation --------------------------------------
    // The 1021 documents omit doc_uuid, action_refs, modified_date and the
    // bezier handle weights entirely. A reader that assumes they exist crashes
    // on these, so this fixture is a liveness test as much as a value test.
    fprintf(stderr, "\n-- 1021 format generation --\n");
    {
        const Moho::Document d = load(dir, "old_1021_generation.moho");
        check(d.valid, "parses despite missing optional fields");
        check(d.version == 1021, "older version recognised",
              QString::number(d.version));
        check(d.totalLayers == 1, "layer read", QString::number(d.totalLayers));
        // The image path is on an ImageLayer-less MeshLayer here, so it must
        // still be picked up by the structural scan.
        check(d.referencedImages.contains("images/legacy.png"),
              "image path found without the newer fields",
              joined(d.referencedImages));
        // The images folder is not beside the fixture, so all are missing --
        // and the reader must say so rather than pretend.
        check(d.imagesMissing == 1 && d.imagesFound == 0,
              "missing images are reported, not hidden",
              QString("%1 missing / %2 found")
                  .arg(d.imagesMissing)
                  .arg(d.imagesFound));
    }

    // ---- nesting, binding and a dangling bone parent -----------------------
    fprintf(stderr, "\n-- nesting and bone binding --\n");
    {
        const Moho::Document d = load(dir, "nested_and_dangling_bone.moho");
        check(d.valid, "parsed");
        // Outer > Inner > (Rigged, Backdrop, Caption) is 5, plus the separate
        // BoneLayer at the top level: 6 in all.
        check(d.totalLayers == 6, "recursive layer count",
              QString::number(d.totalLayers));
        check(d.layerTypes.value("GroupLayer") == 2, "both groups counted");
        check(d.layerTypes.value("TextLayer") == 1, "TextLayer counted");
        check(d.layerTypes.value("ImageLayer") == 1, "ImageLayer counted");

        // Find the region-bound mesh layer and check its binding survived.
        bool foundBinding = false, foundSubset = false, foundHidden = false;
        std::function<void(const QVector<Moho::Layer> &)> walk =
            [&](const QVector<Moho::Layer> &ls) {
                for (const Moho::Layer &l : ls) {
                    if (l.name == "Rigged") {
                        foundBinding = l.parentBone == -1;
                        foundSubset = l.flexibleBoneSubset == "0|1|2";
                        foundSubset = foundSubset &&
                                      l.texturePath == "images/skin.png";
                    }
                    if (l.name == "Inner")
                        foundHidden = !l.visible && l.depth == 1;
                    walk(l.children);
                }
            };
        walk(d.layers);
        check(foundBinding, "flexible (parent_bone = -1) binding preserved");
        check(foundSubset, "flexible bone subset and texture path preserved");
        check(foundHidden, "group visibility and depth preserved");

        check(d.bones.size() == 3, "three bones", QString::number(d.bones.size()));
        // The dangling parent must be reported, not crash or be clamped away.
        int dangling = 0;
        for (const Moho::Bone &b : d.bones)
            if (b.parent >= d.bones.size()) ++dangling;
        check(dangling == 1, "dangling bone parent is visible, not fatal",
              QString("%1 dangling").arg(dangling));

        check(d.referencedImages.contains("images/bg.png") &&
                  d.referencedImages.contains("images/skin.png"),
              "image paths found across layer types",
              joined(d.referencedImages));
    }

    // ---- rejections must always explain themselves ------------------------
    fprintf(stderr, "\n-- rejections --\n");
    {
        Moho::Document d;
        const bool ok = g_read(
            TFilePath(QDir(dir).filePath("not_moho.moho").toStdString()), d);
        check(!ok, "a foreign mime type is rejected");
        check(!d.error.isEmpty() && d.error.contains("mime_type"),
              "rejection names the offending field", d.error);
    }
    {
        Moho::Document d;
        const bool ok = g_read(TFilePath(QDir(dir)
                                             .filePath("truncated.mohoproj")
                                             .toStdString()),
                               d);
        check(!ok, "unparseable JSON is rejected");
        check(!d.error.isEmpty() && d.error.contains("JSON"),
              "rejection says the document is not valid JSON", d.error);
    }
    {
        Moho::Document d;
        const bool ok = g_read(
            TFilePath(QDir(dir).filePath("legacy.anme").toStdString()), d);
        check(!ok, "the pre-11 format is rejected rather than mis-parsed");
        check(!d.error.isEmpty() && d.error.contains("Re-save"),
              "rejection tells the user what to do", d.error);
    }
    {
        Moho::Document d;
        const bool ok = g_read(
            TFilePath(QDir(dir).filePath("plain.zip").toStdString()), d);
        check(!ok, "a ZIP with no project document is rejected");
        check(!d.error.isEmpty(), "rejection carries a reason", d.error);
    }
    {
        Moho::Document d;
        const bool ok = g_read(TFilePath("no_such_file.moho"), d);
        check(!ok, "a missing file is rejected");
        check(!d.error.isEmpty(), "rejection carries a reason", d.error);
    }

    // ---- the manifest is a usable artefact --------------------------------
    fprintf(stderr, "\n-- manifest --\n");
    {
        const QString outDir =
            QDir(QDir::tempPath()).filePath("flare_moho_manifest_test");
        QDir().mkpath(outDir);
        const Moho::Document d = load(dir, "nested_and_dangling_bone.moho");
        const int written = g_manifest(
            TFilePath(QDir(dir)
                          .filePath("nested_and_dangling_bone.moho")
                          .toStdString()),
            d, TFilePath(outDir.toStdString()));
        check(written >= 1, "manifest written", QString::number(written));

        QFile f(QDir(outDir).filePath("moho_manifest.json"));
        check(f.open(QIODevice::ReadOnly), "manifest readable");
        QJsonObject root;
        if (f.isOpen()) {
            const QJsonDocument jd = QJsonDocument::fromJson(f.readAll());
            check(jd.isObject(), "manifest is a JSON object");
            root = jd.object();
        }
        check(root.value("format").toString() == "moho-rig-manifest",
              "manifest is self-describing");
        const QJsonObject census = root.value("census").toObject();
        check(census.value("total_layers").toInt() == d.totalLayers,
              "census layer count matches the reader");
        check(census.value("bones").toInt() == d.bones.size(),
              "census bone count matches the reader");
        check(census.value("keyframes").toInt() == d.keyframes,
              "census keyframe count matches the reader");
        // The layer tree must round-trip through the manifest.
        const QJsonArray layers = root.value("layers").toArray();
        check(layers.size() == d.layers.size(), "top-level layers preserved");
        if (!layers.isEmpty()) {
            const QJsonObject outer = layers.first().toObject();
            check(outer.value("name").toString() == "Outer",
                  "first layer is the outer group", outer.value("name").toString());
            check(outer.contains("layers"), "nested layers preserved");
        }
        // The dangling parent index must be visible in the artefact, so a
        // consumer can tell the rig is damaged.
        bool sawDangling = false;
        for (const QJsonValue &bv : root.value("bones").toArray()) {
            const QJsonObject bo = bv.toObject();
            if (bo.value("name").toString() == "Orphan" &&
                bo.value("parent").toInt(-1) == 99)
                sawDangling = true;
        }
        check(sawDangling, "dangling bone parent recorded in the manifest");
        check(!root.value("images").toObject().value("note").toString().isEmpty(),
              "manifest explains the image-availability caveat");
    }

    // ---- an invalid document must not produce a manifest ------------------
    {
        Moho::Document bad;
        const int n = g_manifest(TFilePath("x.moho"), bad,
                                 TFilePath("y"));
        check(n == 0, "no manifest is written for an unparsed document",
              QString::number(n));
    }

    fprintf(stderr, "\n%s: %d checks, %d failure(s)\n",
            gFail ? "FAILED" : "PASSED", gChecks, gFail);
    return gFail ? 1 : 0;
}
