name: Ask a question
description: Questions relating to Flare only
labels: 'question'
body:
  - type: markdown
    attributes:
      value: |
        Please search existing issues before posting to avoid creating duplicates.
        
        For general support please head over to the Flare Community Forum or consult the [Manual](https://flare-animate.github.io/website/).
  - type: textarea
    attributes:
      label: Ask a question related to Flare
      placeholder: Ex. I'm having trouble building Flare [...]. There's an undocumented feature, what does it do?
    validations:
      required: true
